name: car_rent
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adobe_xd: ^1.1.0+1
  get: any
  font_awesome_flutter: ^8.11.0
  outline_material_icons: ^0.1.1
  flutter_icons: any
  flutter_svg: any
  flutter_spinkit: any
  cached_network_image:
  flutter_rating_bar: ^3.0.1+1
  image_picker: ^0.7.2
  intl:
  google_fonts:
  flutter_map: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/

